//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conf_SubMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Conf_SubMenu()
        {
            this.Conf_SubsubMenu = new HashSet<Conf_SubsubMenu>();
        }
    
        public int ID { get; set; }
        public Nullable<int> MenuID { get; set; }
        public string Name { get; set; }
        public string AreaName { get; set; }
        public string ControllerName { get; set; }
        public string PageName { get; set; }
        public Nullable<bool> IsEnabled { get; set; }
    
        public virtual Conf_Menu Conf_Menu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conf_SubsubMenu> Conf_SubsubMenu { get; set; }
    }
}
