//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Def_Users
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public Nullable<float> password { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
