//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpAllowance
    {
        public int ID { get; set; }
        public Nullable<int> AllowanceTypeID { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual Def_AllowanceTypes Def_AllowanceTypes { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
