//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmpAllowance = new HashSet<EmpAllowance>();
            this.EmpAttendance = new HashSet<EmpAttendance>();
            this.EmpBorrow = new HashSet<EmpBorrow>();
            this.EmpCards = new HashSet<EmpCards>();
            this.EmpElawa = new HashSet<EmpElawa>();
            this.EmpJobs = new HashSet<EmpJobs>();
            this.EmpLeaveEarly = new HashSet<EmpLeaveEarly>();
            this.EmpPenalty = new HashSet<EmpPenalty>();
            this.EmpPromotions = new HashSet<EmpPromotions>();
            this.EmpQualification = new HashSet<EmpQualification>();
            this.EmpRewards = new HashSet<EmpRewards>();
            this.EmpSalaryInfo = new HashSet<EmpSalaryInfo>();
            this.Mission = new HashSet<Mission>();
        }
    
        public int ID { get; set; }
        public int Code { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BithDate { get; set; }
        public string AddressLocation { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> MaritalStateID { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> ActualHireDate { get; set; }
        public Nullable<int> ServiceState { get; set; }
        public Nullable<int> ReligionID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<int> MilitaryServiceID { get; set; }
        public string Telephone { get; set; }
        public Nullable<int> DegreeID { get; set; }
        public Nullable<int> JobID { get; set; }
        public byte[] imagebytes { get; set; }
    
        public virtual Def_Degree Def_Degree { get; set; }
        public virtual Def_Gender Def_Gender { get; set; }
        public virtual Def_Jobs Def_Jobs { get; set; }
        public virtual Def_MaritalStatus Def_MaritalStatus { get; set; }
        public virtual Def_MilitaryService Def_MilitaryService { get; set; }
        public virtual Def_Nationality Def_Nationality { get; set; }
        public virtual Def_Religion Def_Religion { get; set; }
        public virtual Def_ServiceState Def_ServiceState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpAllowance> EmpAllowance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpAttendance> EmpAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpBorrow> EmpBorrow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpCards> EmpCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpElawa> EmpElawa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpJobs> EmpJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpLeaveEarly> EmpLeaveEarly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPenalty> EmpPenalty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpPromotions> EmpPromotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpQualification> EmpQualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpRewards> EmpRewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpSalaryInfo> EmpSalaryInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mission> Mission { get; set; }
    }
}
