//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpLeaveEarly
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<System.DateTime> DateDay { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
        public string reason { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
