//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPenalty
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> PenID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<float> Daysnum { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    
        public virtual Def_Penalty Def_Penalty { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
