//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPromotions
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> DegreeLast { get; set; }
        public Nullable<int> JobLast { get; set; }
        public Nullable<int> DegreeCurrent { get; set; }
        public Nullable<int> JobCurrent { get; set; }
        public string Note { get; set; }
    
        public virtual Def_Degree Def_Degree { get; set; }
        public virtual Def_Degree Def_Degree1 { get; set; }
        public virtual Def_Jobs Def_Jobs { get; set; }
        public virtual Def_Jobs Def_Jobs1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
