//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpSalaryInfo
    {
        public int ID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<decimal> HireSalary { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public Nullable<bool> Insured { get; set; }
        public Nullable<bool> Taxed { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
