//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HREntities : DbContext
    {
        public HREntities()
            : base("name=HREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conf_Menu> Conf_Menu { get; set; }
        public virtual DbSet<Conf_SubMenu> Conf_SubMenu { get; set; }
        public virtual DbSet<Conf_SubsubMenu> Conf_SubsubMenu { get; set; }
        public virtual DbSet<Def_AllowanceTypes> Def_AllowanceTypes { get; set; }
        public virtual DbSet<Def_Attendance> Def_Attendance { get; set; }
        public virtual DbSet<Def_CardType> Def_CardType { get; set; }
        public virtual DbSet<Def_Degree> Def_Degree { get; set; }
        public virtual DbSet<Def_ElawaTypes> Def_ElawaTypes { get; set; }
        public virtual DbSet<Def_Gender> Def_Gender { get; set; }
        public virtual DbSet<Def_Jobs> Def_Jobs { get; set; }
        public virtual DbSet<Def_MaritalStatus> Def_MaritalStatus { get; set; }
        public virtual DbSet<Def_MilitaryService> Def_MilitaryService { get; set; }
        public virtual DbSet<Def_Nationality> Def_Nationality { get; set; }
        public virtual DbSet<Def_Penalty> Def_Penalty { get; set; }
        public virtual DbSet<Def_QualificationTypes> Def_QualificationTypes { get; set; }
        public virtual DbSet<Def_Religion> Def_Religion { get; set; }
        public virtual DbSet<Def_RewardTypes> Def_RewardTypes { get; set; }
        public virtual DbSet<Def_ServiceState> Def_ServiceState { get; set; }
        public virtual DbSet<Def_Users> Def_Users { get; set; }
        public virtual DbSet<EmpAllowance> EmpAllowance { get; set; }
        public virtual DbSet<EmpAttendance> EmpAttendance { get; set; }
        public virtual DbSet<EmpBorrow> EmpBorrow { get; set; }
        public virtual DbSet<EmpCards> EmpCards { get; set; }
        public virtual DbSet<EmpElawa> EmpElawa { get; set; }
        public virtual DbSet<EmpJobs> EmpJobs { get; set; }
        public virtual DbSet<EmpLeaveEarly> EmpLeaveEarly { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<EmpPenalty> EmpPenalty { get; set; }
        public virtual DbSet<EmpPromotions> EmpPromotions { get; set; }
        public virtual DbSet<EmpQualification> EmpQualification { get; set; }
        public virtual DbSet<EmpRewards> EmpRewards { get; set; }
        public virtual DbSet<EmpSalaryInfo> EmpSalaryInfo { get; set; }
        public virtual DbSet<Mission> Mission { get; set; }
    }
}
